language: php
php:
- 5.6
- hhvm
- 7.0
- 7.1
- 7.2
matrix:
  include:
    - php: 7.0
      script:
      - php vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
      after_script:
      - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
before_script:
- travis_retry composer self-update
- travis_retry composer install --no-interaction --prefer-dist
script:
- php vendor/bin/phpunit
